### ISSUE TITLE
Trocar o modo dev de "yes" para o URL do provider

### ISSUE THREAD

**Issue by wgnann** [uspdev/senhaunica-socialite#16]
Isso permite usar o senhaunica-socialite em treinamentos / projetos onde o pessoal não tem acesso à API de OAuth1 da USP.

**Comment by thiagogomesverissimo** [comment]
Podemos dropar a variável:

`SENHAUNICA_DEV=yes`

Em favor de:

`SENHAUNICA_BASE_URL='https://uspdigital.usp.br/wsusuario/oauth'`
