### ISSUE TITLE
Permitir desabilitar route interno users no .env

### ISSUE THREAD

**Issue by ayrtonnotrya** [uspdev/senhaunica-socialite#46]
Caso se queira usar a rota users na aplicação precisa desabilitar a rota interna do senhaunica no arquivo de config a cada deploy.

**Comment by masakik** [comment]
Ola, desculpe não ver antes essa issue.
A configuração está presente no config mas não está exposto no env correto?
Em geral, se a aplicação precisa que seja desabilitada essa rota, alterar no config é suficiente, pois não deve ser uma configuração que dependa de um deploy específico. 
É alguma aplicação do USPDev ou aplicação própria? Se você explicar melhor o contexto podemos ajudar a encontrar uma solução.
